/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#121315',
        'surface-dim': '#121315',
        'surface-card': '#1D1E20',
        'surface-container-lowest': '#0d0e10',
        'surface-container-low': '#1b1c1e',
        'surface-container': '#1f2022',
        'surface-container-high': '#292a2c',
        'surface-container-highest': '#343537',
        'surface-variant': '#343537',
        'surface-bright': '#38393b',
        'background': '#121315',
        'background-deep': '#0B0C0E',
        'primary': '#62df78',
        'primary-fixed': '#7ffc91',
        'primary-fixed-dim': '#62df78',
        'primary-container': '#1ea648',
        'on-primary': '#003912',
        'on-primary-container': '#00320e',
        'on-primary-fixed': '#002107',
        'on-primary-fixed-variant': '#00531d',
        'secondary': '#adc7ff',
        'secondary-container': '#4a8eff',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc7ff',
        'on-secondary': '#002e68',
        'on-secondary-container': '#00285b',
        'on-secondary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#004493',
        'tertiary': '#c1c8c3',
        'tertiary-container': '#8b928e',
        'tertiary-fixed': '#dde4df',
        'tertiary-fixed-dim': '#c1c8c3',
        'on-tertiary': '#2b322f',
        'on-tertiary-container': '#242b28',
        'on-tertiary-fixed': '#161d1a',
        'on-tertiary-fixed-variant': '#414845',
        'on-surface': '#e3e2e4',
        'on-surface-variant': '#bdcab9',
        'on-background': '#e3e2e4',
        'outline': '#879485',
        'outline-variant': '#3e4a3d',
        'surface-tint': '#62df78',
        'inverse-surface': '#e3e2e4',
        'inverse-on-surface': '#2f3032',
        'inverse-primary': '#006e2a',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'status-online': '#009B3E',
        'status-warning': '#FFB800',
        'status-critical': '#FF3B30',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'card-padding': '20px',
        gutter: '24px',
        margin: '32px',
        'container-max': '1440px',
        base: '4px',
      },
      fontFamily: {
        'headline-sm': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'label-sm': ['JetBrains Mono'],
        'label-md': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
